# -*- coding: utf-8 -*-
'''generated by Luji Cui on 2012.03.27;
Function:Waiting animation'''
import wx
import wx.animate
from twisted.internet import  reactor

class WaitFrame(wx.Frame):
	def __init__(self, parent, id,title):
		wx.Frame.__init__(self, parent, id,title,size = (300,500),style = wx.DEFAULT_FRAME_STYLE^(wx.MINIMIZE_BOX|wx.RESIZE_BORDER))
		self.panel = wx.Panel(self, -1)
		self.panel.SetBackgroundColour('orange')
		box = wx.BoxSizer(wx.VERTICAL)
#add the animation widget
		font = wx.Font(12, wx.ROMAN, wx.NORMAL, wx.BOLD)
		gif_fname = "./images/Wait.gif"
		gif = wx.animate.GIFAnimationCtrl(self.panel, id, gif_fname)
		text = wx.StaticText(self.panel, -1, 'Loading data,please wait...')
		text.SetFont(font)
		button = wx.Button(self.panel, 1, '取消')
		gif.GetPlayer()
		gif.Play()
#end

#frame layout
		box.Add(gif, 2, wx.ALIGN_CENTER|wx.TOP, 20)
		box.Add(text, 1, wx.ALIGN_CENTER, 0)
		box.Add(button, 1, wx.ALIGN_CENTER|wx.BOTTOM, 10)
		self.panel.SetSizer(box)
		self.Center()
#end
		self.Bind(wx.EVT_BUTTON,self.Exit,button)

#trigger event:close the WaitFrame
	def Exit(self, event):
		#self.Destroy()
		reactor.stop()
#end

class MyApp(wx.App):
	def OnInit(self):
		frame = WaitFrame(None, -1, "Waiting")
		frame.Show(True)
		return True


if __name__ == "__main__":
	app = MyApp(0)
	app.MainLoop()

