#!/usr/bin/python
# -*- coding: utf-8 -*-
'''generated by Luji Cui on 2011.11.17;
the dialog to show user friend's course information.'''

import wx
import wx.html

class FriendCourse(wx.Dialog):
	def __init__(self,parent,id,title):
		wx.Dialog.__init__(self,None,-1,title,size=(800,550))
		hbox = wx.BoxSizer(wx.VERTICAL)
#add the html widget to show course information in list and box forms
		self.courselist = wx.html.HtmlWindow(self)
		self.coursebox = wx.html.HtmlWindow(self)
		if "gtk2" in wx.PlatformInfo:
			self.courselist.SetStandardFonts()
		if "gtk2" in wx.PlatformInfo:
			self.coursebox.SetStandardFonts()
#end
		self.button = wx.Button(self, 1, 'Close')
		self.Bind(wx.EVT_BUTTON, self.OnClose, self.button)
    #frame layout
		self.Center()
		hbox.Add(self.courselist, 4, wx.EXPAND, 0)
		hbox.Add(self.coursebox, 4, wx.EXPAND, 0)
		hbox.Add(self.button, 1, wx.ALIGN_CENTER|wx.BOTTOM|wx.TOP, 10)
		self.SetSizer(hbox)
    #end

#trigger event:close this frame
	def OnClose(self, event):	
		self.Destroy()
#end

if __name__ == '__main__':
	app = wx.PySimpleApp()
	cframe = FriendCourse(None,-1,'好友课程')
	cframe.ShowModal()
	cframe.Destroy()
