#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''generated by LujiCui on Fri Feb 17 21:17:58 2012;
this frame is a reminder of fresh news.'''

import wx

class TipFrame(wx.Frame):
	def __init__(self,parent,id,title):
		wx.Frame.__init__(self, parent, id, title,style=wx.DEFAULT_FRAME_STYLE|wx.SUNKEN_BORDER,pos=(1400,700),size=(200,120))
		hbox = wx.BoxSizer(wx.VERTICAL)
		self.text = wx.StaticText(self, -1, u"收到最新新闻，请查看!")
		self.button = wx.Button(self, -1, u"确定")
    #define a timer and set 3 seconds as flag
		self.timer = wx.Timer(self)
		self.Bind(wx.EVT_TIMER,self.OnTimer,self.timer)
		self.timer.Start(3000)
    #end
		self.Bind(wx.EVT_BUTTON, self.OnExit, self.button)

		hbox.Add(self.text, 2, wx.ALIGN_CENTER|wx.TOP, 20)
		hbox.Add(self.button, 1, wx.EXPAND|wx.LEFT|wx.RIGHT, 50)
		self.SetSizer(hbox)

#trigger event:show this frame about 3 seconds and then close it
	def OnTimer(self,event):
		self.timer.Stop()
		self.Destroy()
#end

#trigger event:close this frame
	def OnExit(self, event):
		self.Destroy()
#end

if __name__ == '__main__':
	app = wx.PySimpleApp()
	TipFrame(None,-1,'Tips').Show()
	app.MainLoop()
