#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''generated by LujiCui 0.6.3 on Sat Feb  4 20:20:21 2012;
this dialog shows the introduction of this application,including application introduction and developers' information.'''

import wx

class IntroductionFrame(wx.Dialog):
	def __init__(self,parent,id,title):
		wx.Dialog.__init__(self,parent,id,title,size=(700,500))
		self.inform_text = "		This is an open-source software.Everyone can download the source code on\n	(googlecode).This is a platform to collect the informationfrom university's websi\n	te and release the information timely to users.Aboutthis version,you can select t\n	he information about Dean's Office News,Curriculum News and College News.Be\n	sides,you can look up the course and its mark you have learnt.Moreover,you can \n	add your classmates as your friends and know some statistic data the software pre\n	sents for you! \n		If you meet any problem when you use the software,please send e-mail to (goo\n	glegroup)."
		self.author_text = "	CuiLuji,responsible for the software's GUI about Client.\n		E-mail Address:cuiluji@gmail.com\n	GuoDongsheng and HuangJiakun,responsible for the software's server and \n		communication agreement.\n		E-mail Address:\n	HuangLiqiang,responsible for the software's database.\n		E-mail Address:"
		self.notebook_1 = wx.Notebook(self, -1, style=wx.NB_BOTTOM|wx.DOUBLE_BORDER)
		self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
		self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
		self.srdp = wx.StaticBitmap(self, -1, wx.Bitmap("images/ouc.png", wx.BITMAP_TYPE_ANY))
		self.Button = wx.Button(self,wx.ID_OK, 'Close').SetDefault()
		self.introduction = wx.StaticText(self.notebook_1_pane_1, -1, self.inform_text)
		self.authors = wx.StaticText(self.notebook_1_pane_2, -1, self.author_text)
		self.__do_layout()
		self.Center()

#dialog layout
	def __do_layout(self):
		sizer_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_2 = wx.BoxSizer(wx.VERTICAL)
		sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_2.Add(self.srdp, 3, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_6.Add(self.introduction, 0, 0, 0)
		self.notebook_1_pane_1.SetSizer(sizer_6)
		sizer_5.Add(self.authors, 0, 0, 0)
		self.notebook_1_pane_2.SetSizer(sizer_5)
		self.notebook_1.AddPage(self.notebook_1_pane_1, 'Introduction')
		self.notebook_1.AddPage(self.notebook_1_pane_2, 'About the author')
		sizer_2.Add(self.notebook_1, 6, wx.EXPAND, 20)
		sizer_2.Add(self.Button, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_1)
		self.Layout()
#end

if __name__ == "__main__":
	app = wx.PySimpleApp()
	frame_1 = IntroductionFrame(None, -1, "About Me")
	frame_1.Show()
	app.MainLoop()
