#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''generated by LujiCui 0.6.3 on Sat Feb  4 20:20:21 2012;
this frame is to list the people who want to add user as their friend.'''

import wx

class RemindFrame(wx.Frame):
	def __init__(self, parent, id, title):
		wx.Frame.__init__(self, parent, id, title,size=(400,200),style=0)
        #list 4 applications in one page
		self.text_1 = wx.StaticText(self, -1, "name and number_1")
		self.button_1 = wx.Button(self, -1, "同意")
		self.button_2 = wx.Button(self, -1, "不同意")
		self.text_2 = wx.StaticText(self, -1, "name and number_2")
		self.button_3 = wx.Button(self, -1, "同意")
		self.button_4 = wx.Button(self, -1, "不同意")
		self.text_3 = wx.StaticText(self, -1, "name and number_3")
		self.button_5 = wx.Button(self, -1, "同意")
		self.button_6 = wx.Button(self, -1, "不同意")
		self.text_4 = wx.StaticText(self, -1, "name and number_4")
		self.button_7 = wx.Button(self, -1, "同意")
		self.button_8 = wx.Button(self, -1, "不同意")
        #end
		self.Center()

		self.__do_layout()
#frame layout
	def __do_layout(self):
		sizer_1 = wx.BoxSizer(wx.VERTICAL)
		grid_sizer_1 = wx.GridSizer(5, 2, 0, 0)
		grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
		grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
		grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
		grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
		grid_sizer_1.Add(self.text_1, 0, 0, 0)
		grid_sizer_2.Add(self.button_1, 0, 0, 0)
		grid_sizer_2.Add(self.button_2, 0, 0, 0)
		grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
		grid_sizer_1.Add(self.text_2, 0, 0, 0)
		grid_sizer_3.Add(self.button_3, 0, 0, 0)
		grid_sizer_3.Add(self.button_4, 0, 0, 0)
		grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)
		grid_sizer_1.Add(self.text_3, 0, 0, 0)
		grid_sizer_4.Add(self.button_5, 0, 0, 0)
		grid_sizer_4.Add(self.button_6, 0, 0, 0)
		grid_sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)
		grid_sizer_1.Add(self.text_4, 0, 0, 0)
		grid_sizer_5.Add(self.button_7, 0, 0, 0)
		grid_sizer_5.Add(self.button_8, 0, 0, 0)
		grid_sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)
		sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_1)
		#sizer_1.Fit(self)
		self.Layout()
#end

if __name__ == "__main__":
	app = wx.PySimpleApp()
	frame = RemindFrame(None, -1, "REMIND")
	frame.Show()
	app.MainLoop()
