#!/usr/bin/python
# -*- coding: utf-8 -*-
'''generated by Luji Cui on 2011.11.17;
when user click the news headline to display news in this new frame.'''

import wx
import wx.html
import wx.lib.agw.hyperlink as hl

class ChildFrame(wx.Dialog):
	def __init__(self,parent,id,title):
		wx.Dialog.__init__(self,None,-1,title,size=(900,650))
#add frame widgets
		self.bButton = wx.Button(self, -1, u"关闭",(30,30))
		self.sb = wx.StaticBox(self, -1, u"最新新闻",(30,70),(850,580))
		self.html = wx.html.HtmlWindow(self,-1,(50,100),(810,550))
		if "gtk2" in wx.PlatformInfo:
			self.html.SetStandardFonts()
#end
#		wx.CallAfter(html.SetPage,self.url)		
		self.Bind(wx.EVT_BUTTON,self.OnBack,self.bButton)
		self.Center()		
#trigger event:close this frame
	def OnBack(self,event):
		self.Destroy()

#if __name__ == '__main__':
#	app = wx.PySimpleApp()
#	cframe = ChildFrame(None,-1,'选课系统新闻')
#	cframe.Show()
#	app.MainLoop()
