# -*- coding: UTF-8 -*-
# ----
# @generated by Jiakun Huang on 2012.05.16
# ----
#服务器端守护进程
import time
import CourseMain
from news import NewsMain
def grabNews():
#        try:
    print time.ctime()+"\t开始更新新闻"
    NewsMain.InsertJiaoWuChu()
    NewsMain.InsertSystemOfCourse()
    NewsMain.InsertGongCheng()
#        NewsMain.InsertGuanLi()
    NewsMain.InsertHaiHuan()
    NewsMain.InsertHaiSheng()
    NewsMain.InsertHuanKe()
    NewsMain.InsertJiJiao()
    NewsMain.InsertJingJi()
    NewsMain.InsertShiPin()
    NewsMain.InsertShuiChan()
    NewsMain.InsertShuXue()
#        NewsMain.InsertWaiYu()
    NewsMain.InsertWenXin()
    NewsMain.InsertYiShu()
    NewsMain.InsertYiYao()
    print time.ctime()+"\t新闻更新结束"
#        except Exception:
#            print time.ctime()+"\t"+"新闻抓取操作失败，60s后重试。"
#            print "错误类型："
#            print traceback.print_exc()
if __name__=="__main__":
    while True:
        grabNews()
        time.sleep(60)