#!/usr/bin/python
# -*- coding: utf-8 -*-
'''generated by Luji Cui on 2011.11.10;
the optionframe to help user choose the information they need.'''

import wx


from user.correspond.connect import SetOne 

class OptionFrame(wx.Frame):
	def __init__(self,protocol):
		self.protocol=protocol     #hjk,初始化协议protocol
		wx.Frame.__init__(self,None,-1,'Options',size=(340,380),style=wx.DEFAULT_FRAME_STYLE ^ (wx.RESIZE_BORDER))
		panel = wx.Panel(self,-1)
		self.Bind(wx.EVT_CLOSE,self.OnCloseWindow)
#add frame widgets
		wx.StaticText(panel,-1,"请选择你想获得的动态信息：",(20,20))
		self.cb1 = wx.CheckBox(panel,-1,"选课系统公告",(100,60),(150,20))
		self.cb2 = wx.CheckBox(panel,-1,"所在院系新闻",(100,100),(150,20))
		self.cb3 = wx.CheckBox(panel,-1,"教务处新闻",(100,140),(150,20))
		List = ["是","否"]
		self.rb = wx.RadioBox(panel,-1,"是否下次显示该对话框：",(20,200),wx.DefaultSize,List,2,wx.RA_SPECIFY_COLS)
		wx.Button(panel,1,"确定",(130,300)).SetDefault()
#end

#set the trigger event
		self.Bind(wx.EVT_CHECKBOX,self.OnCount,id=self.cb1.GetId())
		self.Bind(wx.EVT_CHECKBOX,self.OnCount,id=self.cb2.GetId())
		self.Bind(wx.EVT_CHECKBOX,self.OnCount,id=self.cb3.GetId())
		self.Bind(wx.EVT_RADIOBOX,self.OnRadio,id=self.rb.GetId())
		self.Bind(wx.EVT_BUTTON,self.OnClose,id=1)
#end
		self.Center()

#function:save user's choice
	def OnCount(self,event):
		SetOne(self.cb1.GetValue(),self.cb2.GetValue(),self.cb3.GetValue())		
#end

#trigger event:gain user's choice
	def OnRadio(self,event):
		return self.rb.GetSelection()
#end

#trigger event:hide the optionframe and skip to userframe
	def OnClose(self,event):
#		uf = MyFrame(None,-1)
#		uf.Show()
    #hjk
		self.sendOption()
		self.TurntoUf()
		self.Hide()
    #end
#end
	
#trigger event:close the optionframe
	def OnCloseWindow(self,event):
		self.OnClose(event)
    #hjk
    #转至第三个窗口，初始化其协议
	def TurntoUf(self):
		if  self.protocol.factory.ufgui==None:
			from user.UserModule import MyFrame
			uf=MyFrame(None,-1,self.protocol)
			uf.protocol.factory.ufgui=uf
			self.protocol.initPage()
			uf.Show()     
		else:
			self.protocol.factory.ufgui.RefreshModule()
	#发送更改后的感兴趣的模块
	def sendOption(self):
		#未选中的发送过去，数据库将其改为0
		information="options"
		#flag
		if self.rb.GetSelection()==1:
			information=information+"|||"+"0"
		else:
			information=information+"|||"+"1"
		#jwcnews
		if self.cb1.GetValue()==False:
			self.protocol.options[0]=False
			information=information+"|||"+"0"
		else:
			self.protocol.options[0]=True
			information=information+"|||"+"1"
		#xknews
		if self.cb2.GetValue()==False:
			self.protocol.options[1]=False
			information=information+"|||"+"0"
		else:
			self.protocol.options[1]=True
			information=information+"|||"+"1"
		#facultynews
		if self.cb3.GetValue()==False:
			self.protocol.options[2]=False
			information=information+"|||"+"0"
		else:
			self.protocol.options[2]=True
			information=information+"|||"+"1"
		self.protocol.sendLine(information)
        #end
#end

